sudo: false
language: python

matrix:
  include:
    - python: "3.6-dev"
      env: TEST_CMD="flake8"
    - python: "3.6"
      env: TEST_CMD="./tests/mypy_selftest.py"
    - python: "3.5"
      env: TEST_CMD="./tests/mypy_test.py --no-implicit-optional"
    - python: "3.4"
      env: TEST_CMD="./tests/check_consistent.py"
    - python: "2.7"
      env: TEST_CMD="./tests/pytype_test.py --num-parallel=4"
      sudo: true

install:
  # pytype needs py-2.7, mypy needs py-3.3+. Additional logic in runtests.py
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6-dev' ]]; then pip install -r requirements-tests-py3.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then pip install -U git+git://github.com/python/mypy git+git://github.com/python/typed_ast; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements-tests-py2.txt; wget https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.6.tar.bz2; sudo tar xjf python-3.6.tar.bz2 --directory /; fi

script:
  - $TEST_CMD
