name: Publish hotfix artifacts in Space

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'Hotfix tag to publish'
        required: true

jobs:
  publish-current:
    name: Publish hotfix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag-name }}

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        run: chmod +x gradlew

      - name: Run Gradle
        run: ./gradlew publishMainPublicationToSpaceRepository
        env:
          MAVEN_SPACE_USERNAME: ${{secrets.MAVEN_SPACE_USERNAME}}
          MAVEN_SPACE_PASSWORD: ${{secrets.MAVEN_SPACE_PASSWORD}}
