name: Publish artifacts in Space

on:
  release:
    types: [ published ]
  push:
    branches:
      - main
      - 'releases/**'
      - 'archived-releases/**'

jobs:
  publish-current:
    name: Publish current IJP version (main)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        run: chmod +x gradlew

      - name: Run Gradle
        run: ./gradlew publishMainPublicationToSpaceRepository --no-daemon
        env:
          MAVEN_SPACE_USERNAME: ${{secrets.MAVEN_SPACE_USERNAME}}
          MAVEN_SPACE_PASSWORD: ${{secrets.MAVEN_SPACE_PASSWORD}}
          PGP_PASSWORD: ${{secrets.PGP_PASSWORD}}
          PGP_PRIVATE_KEY: ${{secrets.PGP_PRIVATE_KEY}}

  publish-older:
    name: Publish older IJP version(s)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch-name:
          - releases/233
          - releases/241
          - releases/242

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch-name }}

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        run: chmod +x gradlew

      - name: Run Gradle
        run: ./gradlew publishMainPublicationToSpaceRepository --no-daemon
        env:
          MAVEN_SPACE_USERNAME: ${{secrets.MAVEN_SPACE_USERNAME}}
          MAVEN_SPACE_PASSWORD: ${{secrets.MAVEN_SPACE_PASSWORD}}
          PGP_PASSWORD: ${{secrets.PGP_PASSWORD}}
          PGP_PRIVATE_KEY: ${{secrets.PGP_PRIVATE_KEY}}
