#cargo_features=["strip"]

[package]
name = "xplat-launcher"
version = "0.1.0"
edition = "2021"
rust-version = "1.62.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
#strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"

[features]

[dependencies]
log = "0.4.14"
native-dialog = "0.6.3"
serde = { version="1.0.136", features = ["derive"] }
serde_json = "1.0.79"
is_executable = "1.0.1"
simplelog = "0.12.0"
thiserror = "1.0.30"
jni = { version="0.19.0" }
libloading = "0.7.3"
jni-sys = "0.3.0"
path-absolutize = "3.0.13"

[dev-dependencies]
junction = "0.2.0"
fs_extra = "1.2.0"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9.3"