version = "1.0.1"
# Requires a version of numpy with a `py.typed` file
requires = ["numpy>=1.20", "pandas-stubs<2.2.3.250527", "types-shapely", "pyproj"]
upstream_repository = "https://github.com/geopandas/geopandas"

[tool.stubtest]
# libproj-dev and proj-bin are required to build pyproj if wheels for the
# target Python version are not available.
apt_dependencies = ["libproj-dev", "proj-bin"]
