version = "4.4.4"
# GitHub mirror of https://hg.reportlab.com/hg-public/reportlab/file
upstream_repository = "https://github.com/MrBitBucket/reportlab-mirror"

[tool.stubtest]
apt_dependencies = ["libcairo2-dev"]
extras = ["pycairo"]
